FROM scratch
COPY busybox /bin/busybox
RUN ["/bin/busybox", "--install", "/bin"]
COPY kubo_v0.19.0_linux-amd64.tar.gz /kubo.tar.gz
CMD ["/bin/sh", "-c", "tar -xzf /kubo.tar.gz && /kubo/ipfs daemon --init"]
