[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "/usr/bin/solc"
offline = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",  # Добавьте /contracts/
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    # Удалите эту строку: "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]