name: Foundry CI

on: [push]

jobs:
  test_labs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lab: [lab1, lab2]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          foundryup
          
      - name: Setup ${{ matrix.lab }}
        run: |
          cd ${{ matrix.lab }}
          forge install
          
      - name: Test ${{ matrix.lab }}
        run: |
          cd ${{ matrix.lab }}
          forge test
          
      - name: Check formatting in ${{ matrix.lab }}
        run: |
          cd ${{ matrix.lab }}
          forge fmt --check
