name: Security Scan
on: [push, pull_request]

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Slither
        run: |
          pip install slither-analyzer
          slither . --checklist --fail-medium > report.md
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: slither-report
          path: report.md