version: '3.8'

services:
  api:
    build: .
    ports: ["8080:8080"]
    depends_on:
      - ipfs
      - anvil
  ipfs:
    image: ipfs/go-ipfs:v0.19.0
    ports: ["5001:5001"]
  anvil:
    image: ghcr.io/foundry-rs/foundry:nightly
    command: [
      "anvil",
      "--host", "0.0.0.0",  # Явно разрешаем внешние подключения
      "--port", "8545",
      "--http",
      "--no-rate-limit",
      "--silent"
    ]
    ports:
      - "8545:8545"